"use client";

import * as React from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";

import {
  shortlinkFormSchema,
  type ShortlinkFormValues,
  type ShortlinkCreateInput,
} from "../model/shortlinkSchema";
import { ShortlinkFormFields } from "./ShortlinkFormFields";
import { useCreateShortlink } from "../hooks/useShortlinkCrud";

import { DialogForm } from "@/components/form/DialogForm";
import type { LiteListe } from "@/types/lists";
import {
  buildCreateShortlinkPayload,
  createInitialShortlinkValues,
} from "../lib/transformers";

type Props = {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  merchantId?: string;
  merchantsLite?: LiteListe[];
  initialLandingId?: string;
  onSuccess?: () => void;
};

export function CreateShortlinkDialog({
  open,
  onOpenChange,
  merchantId,
  merchantsLite = [],
  initialLandingId,
  onSuccess,
}: Props) {
  const defaultValues = React.useMemo(
    () => createInitialShortlinkValues(merchantId ?? "", initialLandingId ?? ""),
    [merchantId, initialLandingId]
  );

  const methods = useForm<ShortlinkFormValues>({
    resolver: zodResolver(shortlinkFormSchema),
    defaultValues,
    mode: "onSubmit",
  });

  const { reset } = methods;

  const { mutateAsync, isPending } = useCreateShortlink<
    ShortlinkCreateInput,
    { id?: string }
  >({
    onSuccess: () => {
      reset(defaultValues);
      onSuccess?.();
      onOpenChange(false);
    },
  });

  React.useEffect(() => {
    if (open) {
      reset(defaultValues);
    }
  }, [open, defaultValues, reset]);

  const onSubmit = (values: ShortlinkFormValues) => {
    mutateAsync(buildCreateShortlinkPayload(values));
  };
  
  type MethodsWithSlot = typeof methods & { _slot?: React.ReactNode };
  (methods as MethodsWithSlot)._slot = (
    <ShortlinkFormFields
      mode="create"
      disabled={isPending}
      merchantId={merchantId}
      merchantsLite={merchantsLite}
    />
  );

  return (
    <DialogForm<ShortlinkFormValues>
      open={open}
      onOpenChange={(next) => {
        if (!next) reset(defaultValues);
        onOpenChange(next);
      }}
      title="Create Shortlink"
      description="Select the landing and options. The code will be generated by the API."
      methods={methods}
      onSubmit={onSubmit}
      isBusy={isPending}
      isReady
      submitLabel={isPending ? "Creating..." : "Create"}
    />
  );
}
